### ISSUE TITLE
[Backend/DailySummary] 일일요약에 사용할 데이터리스트 API작성 요청

### ISSUE THREAD

**Issue by jjun990908** [kookmin-sw/capstone-2023-11#115]
## ✨ Description

일일요약에 사용할 데이터들 리스트 API작성

필요 데이터
음식 사진 리스트
해당 사진들에서 인식된 음식 리스트(음식, 칼로리, 영양소(탄단지))
사진 등록 시간
등록한 운동 리스트 (이름, 시간, 시간당 칼로리)
운동 등록 시간

## ✅ To Do List

- [ ] api 작성

**Comment by CULRRY** [comment]
[완]
