### ISSUE TITLE
[Backend/SeniorSummary] 주간 데이터 요약에 필요한 데이터리스트 API작성 요청

### ISSUE THREAD

**Issue by jjun990908** [kookmin-sw/capstone-2023-11#124]
## ✨ Description

일일요약에 사용할 데이터들 리스트 API작성 요청

필요데이터
사용자 정보 (이름, 성별, 나이, 몸무게, 키, 질병)
일일 칼로리 (어제포함 이전 7일)
영양소 (단백질, 탄수화물, 지방, 콜레스테롤, 나트륨)
	   - 7일치 일일 총합
운동 (7일치 일일 소모 칼로리 총합)

## ✅ To Do List

- [ ] API 작성

**Comment by jjun990908** [comment]
<img width="446" alt="스크린샷 2023-05-04 오후 2 28 27" src="https://user-images.githubusercontent.com/39405559/236119028-047de341-4b9a-4a23-ab08-9ae4fbb228ba.png">

이런 형식으로 진행중이었습니다.
편하게 변경하셔도 됩니다.

**Comment by CULRRY** [comment]
`{
  "name": "홍길동",
  "gender": "MALE",
  "age": 7,
  "weight": 0,
  "height": 0,
  "medicalHistory": [
    {
      "kor": "고혈압",
      "eng": "highBloodPressure",
      "description": null
    },
    {
      "kor": "당뇨",
      "eng": "diabetes",
      "description": null
    }
  ],
  "drinkings": 0,
  "smoke": 1,
  "weeklyFoodNutrientSum": [
    {
      "date": "2023-04-27",
      "calorie": 1,
      "carbohydrate": 2,
      "protein": 2,
      "fat": 2,
      "cholesterol": 2,
      "natrium": 2
    },
    {
      "date": "2023-04-28",
      "calorie": 1,
      "carbohydrate": 2,
      "protein": 2,
      "fat": 2,
      "cholesterol": 2,
      "natrium": 2
    },
    {
      "date": "2023-04-29",
      "calorie": 1,
      "carbohydrate": 2,
      "protein": 2,
      "fat": 2,
      "cholesterol": 2,
      "natrium": 2
    },
    {
      "date": "2023-04-30",
      "calorie": 0,
      "carbohydrate": 0,
      "protein": 0,
      "fat": 0,
      "cholesterol": 0,
      "natrium": 0
    },
    {
      "date": "2023-05-01",
      "calorie": 1,
      "carbohydrate": 2,
      "protein": 2,
      "fat": 2,
      "cholesterol": 2,
      "natrium": 2
    },
    {
      "date": "2023-05-02",
      "calorie": 2,
      "carbohydrate": 4,
      "protein": 4,
      "fat": 4,
      "cholesterol": 4,
      "natrium": 4
    },
    {
      "date": "2023-05-03",
      "calorie": 1,
      "carbohydrate": 2,
      "protein": 2,
      "fat": 2,
      "cholesterol": 2,
      "natrium": 2
    }
  ],
  "weeklyExerciseInfo": [
    {
      "date": "2023-04-27",
      "calorie": 0,
      "hour": 0,
      "count": 0
    },
    {
      "date": "2023-04-28",
      "calorie": 0,
      "hour": 0,
      "count": 0
    },
    {
      "date": "2023-04-29",
      "calorie": 0,
      "hour": 0,
      "count": 0
    },
    {
      "date": "2023-04-30",
      "calorie": 0,
      "hour": 0,
      "count": 0
    },
    {
      "date": "2023-05-01",
      "calorie": 0,
      "hour": 0,
      "count": 0
    },
    {
      "date": "2023-05-02",
      "calorie": 0,
      "hour": 0,
      "count": 0
    },
    {
      "date": "2023-05-03",
      "calorie": 0,
      "hour": 0,
      "count": 0
    }
  ]
}`
