### ISSUE TITLE
[Backend/GuardianService] 유저 코드를 이용한 API 호출 구현

### ISSUE THREAD

**Issue by hayounSong** [kookmin-sw/capstone-2023-11#162]
## ✨ Description

보호자 페이지용 API 호출 구현

## ✅ To Do List

- [x] 메인페이지 API 
- [x] 캘린더(운동, 음식) 기록 API
- [x] 일간 보고서 기록 API
- [x] 건강 분석 데이터 API
- [x] 노인 추가 기능 API
- [x] 연결되어있는 노인 확인 API
- [x] 시니어 연결 끊기 API

**Comment by CULRRY** [comment]
완료
