### ISSUE TITLE
[Backend/SeniorMypage] 시니어 마이페이지 개인정보 수정 api 요청

### ISSUE THREAD

**Issue by jjun990908** [kookmin-sw/capstone-2023-11#167]
## ✨ Description

시니어 마이페이지 개인정보 수정 api 요청
수정해야할 개인정보
키, 몸무게, 생년월일, 성별, 질병, 이메일, 흡연주기, 음주주기

## ✅ To Do List

- [x] api 작성
- [x] api 명세서 작성

**Comment by CULRRY** [comment]
완료
