### ISSUE TITLE
[Backend/Calendar] 캘린더에 사용할 데이터들의 날짜 API작성

### ISSUE THREAD

**Issue by jjun990908** [kookmin-sw/capstone-2023-11#94]
## ✨ Description

캘린더에 사용할 데이터들의 날짜 API작성
운동, 영양소 데이터들에 대한 입력 유무에 해당하는 날짜 형식의 api 작성 요청

## ✅ To Do List

- [ ] 필요 데이터 : 입력된 운동의 날짜 리스트, 입력된 음식의 날짜 리스트

**Comment by CULRRY** [comment]
> 요청 api 데이터 형식 Ex) { meal : ["2023-04-06", "2023-04-11", "2023-04-16"], workout : ["2023-04-06", "2023-04-11", "2023-04-20"], }

확인이요
